export declare enum ERROR_LIST {
    ANDROID_SDK_NOT_FIND = "ANDROID_SDK_NOT_FIND",
    ANDROID_ADB_NOT_FIND = "ANDROID_ADB_NOT_FIND",
    ANDROID_EMULATOR_NOT_FIND = "ANDROID_EMULATOR_NOT_FIND",
    ANDROID_NDK_NOT_FIND = "ANDROID_NDK_NOT_FIND",
    IOS_XCODE_NOT_INSTALLED = "IOS_XCODE_NOT_INSTALLED"
}
export declare const ANDROID_SDK_NOT_FIND: Error;
export declare const ANDROID_ADB_NOT_FIND: Error;
export declare const ANDROID_EMULATOR_NOT_FIND: Error;
export declare const ANDROID_NDK_NOT_FIND: Error;
export declare const IOS_XCODE_NOT_INSTALLED: Error;
